cuvva/cuvva-public-go

tools/cdep/commands/update_default.go

It was never unstable on prod - just a problem on nonprod while it had several envs
Now we're running most envs on k8s, it's stable everywhere

cdep: remove Rancher warning

---

lib/jsonschema/filesystem.go

```
//go:embed *.json
var fs embed.FS
var schema = jsonschema.NewFS(fs).LoadJSONExt
...
zs.Register("view_subscriptions", "2019-11-03", schema("view_subscriptions"), rpc.ViewSubscriptions)
```

jsonschema: add filesystem loader for use with embed

---

lib/postcodesio/client.go
lib/postcodesio/client_test.go

As per ongoing conversations, this is not strictly needed but it will keep the `golangci-lint` quiet/happy.
more information: [https://caddyserver.com/docs/extending-caddy#interface-guards](https://caddyserver.com/docs/extending-caddy#interface-guards)

postcodesio: add interface guards

---

lib/config/common.go

this is so that apps which use redis as a cache can still use the connection pool to attempt to connect to redis later even if redis is down when they boot

config: redis return client even on failed ping

---

lib/middleware/request/context.go
lib/middleware/request/context_test.go

This PR changes the behaviour within the `ForkContext` request middleware method such that when the context is cloned, it can clone any and all values, rather than the crpc-specific values.

request middleware: context: clone all context values

---

lib/jsonclient/jsonclient_test.go

PR to fix broken test: gock version bump matches content-type header, and fails the test based on the charset we provide: `application/json; charset=utf-8` which it does not expect.

jsonclient: fix gock version bump broken test matcher

---

cmd/cdep/README.md
tools/cdep/git/monorepo.go

This issue has been faced at two occasions. The issue still present so this piece of tweak solves it by increasing the context timeout and obviously controlling it ourselves within our code. The previous fix was directly in the third party repository however when looking at the `List` function closely it proxies the call to `ListContext` function by attaching a content with timeout. We are now calling `ListContext` with our context.

cdep: use ListContext instead of List to prevent/control context timeout

---

go.mod
lib/config/common.go

allow pre-allocating a listener before running the server
- can bootstrap separately from running meaning it takes less time to attach the handler to the socket
- socket already being open means tests can connect to the socket to send http requests while the handler hasn't been attached in a separate go routine
- basically means no time.Sleep() in acceptance/system/functional tests
run with context:
- when running the app in integration tests, this allows us to shut the app down (we couldn't do this before)
listen on other signals:
- it wasn't shutting down gracefully when I used ctrl+c, it was only coded for k8s
cleaner code:
- acquire a context with signal termination separately
- use errgroup instead of the same thing but messier with err channel ourselves
other things to think about: …

run server with context and pre-allocated listener

---

lib/checkmot/checkmot.go
lib/checkmot/client.go
lib/checkmot/client_test.go

Some VRMs return multiple vehicle objects with different lists of MOT tests but all vehicle information is the same, in these cases merge the MOT test lists and return a single result.
I have opened a ticket with the external API support team regarding this undocumented response scenarios.

checkmot: merge results when multiple identical vehicles

---

lib/checkmot/client.go
lib/checkmot/roundtripper.go

you can use the command to see what the idle timeout is on your connection server side: 
```
time openssl s_client -connect beta.check-mot.service.gov.uk:443
```
The default go client idle timeout is 90 seconds, and the server will not let us use keepalives to keep the connection alive for longer than 60 seconds. 
So currently we see this error when we try to re-use an idle connection that we think should still work:
```
GET /trade/vehicles/mot-tests request failed: Get "https://beta.check-mot.service.gov.uk/trade/vehicles/mot-tests?registration=CUV001": read tcp 10.8.223.4:41318->45.60.65.113:443: read: connection reset by peer
```
- **You must have a lower idle timeout on the client that on the server to avoid connection resets when the connection is attempted to be used**
- also …

checkmot: avoid network connection reset

---

lib/clog/clog.go
lib/crpc/client.go
lib/servicecontext/servicecontext.go

I'm pretty confident that the two values copied from `version` have never been used in any codebase. They will always be the same as the values in `version`, because this library offers no way to override them. Can undo this bit if you want though
I would recommend deprecating & removing the older servicecontext methods - they're quite inflexible and prevent running multiple services in the same runtime

context-based use for `servicecontext`

---

lib/cher/error.go
lib/cher/error_test.go

sometimes we call other internal services
- if they return a cher we usually want to just pass that along
- if they return an error we want to wrap it so we get the context required to know what failed
another approach could be in our http response handler to check if the requests error has any cher wrapped in it anywhere, but the problem is that would affect all our codebase and so is much riskier.

cher: add WrapIfNotCher func

---

lib/config/common.go

mongo lib actually has a connect timeout options, but we use our own context timeout anyhow.
the whole config package here really makes it hard to customise or configure anything, its like a big wall put in front of a useful package.
this is the least invasive way to allow me to timeout integration tests which need to connect to mongo. I intend to skip tests with a message "unable to connect to mongo" to allow engineers to run the test suite while not having database services available. Therefore showing skip messages instead of errors.
waiting 10 seconds for those tests to skip is unreasonable, so we need to configure the timeout.

config: configurable mongo connect timeout for tests

---

lib/soap/soap.go

The decoder wasn't decoding the interface value properly without this tag
According to the Go [docs](https://pkg.go.dev/encoding/xml#Unmarshal):
>If the XML element contains a sub-element that hasn't matched any
of the above rules and the struct has a field with tag ",any",
unmarshal maps the sub-element to that struct field.
Example of the issue: https://go.dev/play/p/sZTC4jwaXQb

soap: add xml tag to the Content field of header and body

---

lib/config/common.go

By default (and as it stands in this library), MongoDB uses the `local` read concern. The documentation states:
> The query returns data from the instance with no guarantee that the data has been written to a majority of the replica set members (i.e. may be rolled back).
Given this library enforces majority writes, and read-after-write consistency is pretty important, I think it should also enforce majority reads. Then data becomes visible at the same point where it's considered to have been written successfully.
The documentation also highlights that performance is comparable to other read concerns, so this benefit comes without any caveats/downsides/tradeoffs:
> To fulfill read concern "majority", the replica set member returns data from its in-memory view of the data at the …

mongodb: use majority read-concern

---

lib/pinpoint/pinpoint.go

The Pinpoint API contract has changed (without versioning 🥳). These are the new data types.

pinpoint: updated API contracts

---

lib/cher/error.go
lib/cher/error_test.go

unknown errors not being wrapped means you have no idea about anything 😂 
preferably it wouldn't be possible to have a cher code "unknown" since it can't be a "handled error"
but that is a probably a bit too much to unpick, so wrap "unknown" codes instead.

cher: WrapIfNotCherCodes

---

lib/crpc/server.go

this is an attempt to reduce error log noise.
if we try to write the response to the client and they have closed the connection, this isn't an error that we can do anything about, so don't return an error.
it is hard to test this, locally if I cancel my http request when paused before the response writing, I don't get an error when it writes, but perhaps you need to have a TCP router in between the client and server which has closed the connection.

crpc: broken pipe on response write is ok

---

go.mod
tools/oncallcalc/app/list_pd_shifts.go

- we've been using deprecated endpoint from the pargerduty library
- ideally we'll need more iteration to pass the context through from the cobra command

oncallcalc: uses new pagerduty function with context

---

.github/workflows/golangci-lint.yml
go.mod
lib/dln/dln.go
lib/middleware/request/json_error.go

- we recently upgraded to go 1.18 but did not upgrade our linter to latest
- fix deprecated usage of `strings.Title()` in favour of `cases.Title()`
- fix wrong usage of `err` when attempting to cast it

linting: use proper err, upgrade linting, fix deprecated method

---

lib/clog/clog.go
lib/clog/clog_test.go

this will stop errors logs showing up when the apps cancel a request because the user changes screen, making it behave the same as normal context cancelled errors in golang.
this is because the postgres library we use has a weird error custom error for context cancelled.

clog: info level postgres context cancelled logs

---

lib/config/common.go

this function is only used by two services at the moment to be able to allocate a http port before booting the whole app, this feature allows us to easily boot the app for testing on ephemeral ports.
rather than have this code understand logging, and therefore having to globally configure a logger or pass a logger in, we should instead log in the caller of this function.

remove listening log

---

tools/cdep/app/add_config.go

```
WARN[0009] Custom branch is going to be overriden, old: reject-mismatch-vrm, new: master, path: /Users/jules/code/config/nonprod/avocado/service/service-ltm.json
```

cdep: show env when override someones branch

---

lib/cher/error.go
lib/cher/third_party_timeout.go
lib/cher/third_party_timeout_test.go
lib/workerpool/pool.go

This will allow us to reduce error log noise by explicitly handling third party timeouts in time endpoints, allow the cher error code to propagate all the way up to the service which is controlling the request.
That service and all services in between can log it as a warning.
We can then add a generic alarm on each service which watches for the error code `third_party_timeout` and will fire only if there are more than X warnings in Y time.

cher: third party timeout

---

lib/cher/third_party_timeout_test.go
lib/clog/clog.go

This PR will reduce error log noise for normal occurrences of requests which are cancelled by our clients when a customer changes screen while the screen is loading.

clog: info level logs on cancelled pgx pool connect

---

tools/cdep/app/update.go
tools/cdep/cdep.go

`config_not_on_mater` should be `config_not_on_master`.
OG error
```
Error: config_not_on_mater
```

cdep: fix error typo

---

tools/cdep/app/add_config.go
tools/cdep/app/update.go
tools/cdep/app/update_default.go
tools/cdep/paths/services.go
tools/cdep/systems.go

during `update service` if the json file doesn't exist, try the yaml file
during `update-default service` if it encounters a yaml file, it sets the branch and commit in the file rather than removing it. (no such thing as _base.yaml)
this allows up to cdep services in the argocd managed pretzel environment

cdep: support yaml files for services

---

.gitignore
lib/middleware/request/context.go
lib/restbase/content_test.go

Enable forked contexts to recover from panics

context: added panic recovery to forked contexts

---

tools/cdep/app/publish_slack.go
tools/cdep/app/update.go
tools/cdep/app/update_default.go
tools/cdep/parsers/parse.go
tools/cdep/paths/terra.go
tools/cdep/types.go

this adds a new type of deployable to cdep `terra`
Usage:
```
cdep update terra pretzel aws-env
cdep update terra all aws-env
cdep update terra pretzel aws-env -b my-branch
```
It also adds a new overrule check to allow me to cdep my config branch that I am using to develop the new github action to auto deploy.
```
cdep update --overrule-checks config_not_on_master terra pretzel aws-env
```
- this also fixes an issue where git shell commands executed wouldn't show their error output because only standard output was being shown.
The new config files exist in this PR https://github.com/cuvva/config/pull/471/files#diff-7190132d243af45f4e7425967f39f3f9d19b79dba215bca76e6d8ecf743f206a

cdep: add terraform workspace types

---

tools/cdep/app/add_config.go

cdep is failing to remove the custom branch if it contains full stops or other characters

cdep: fix an issue with other characters in branch names

---

tools/cdep/app/add_config.go

the last change broke the yaml files
this makes the dot in branch names work in yaml files

cdep: revert yaml branch regex, add dot

---

go.mod
go.sum
tools/cdep/app/update.go
tools/cdep/app/update_default.go
tools/cdep/commands/update.go
tools/cdep/commands/update_default.go
tools/cdep/parsers/parse.go
tools/cdep/parsers/type.go

people are having problems with the go git client authorisation, this allows them to specify the commit instead of it looking up the latest.
this means they can still use the tool to avoid mistakes.
```
cdep update service avocado motor-coverage -b branch -c branch-commit-hash
cdep update service all motor-coverage -c master-commit-hash
cdpe update-default service all -c master-commit-hash
```

cdep commit option

---

lib/crpc/client.go
lib/jsonclient/jsonclient.go
lib/jsonclient/jsonclient_test.go

- `Do` method now takes optional request modifier functions to be applied to the request object
- This allows us to customise headers, e.g. allowing us to pass through the original client metadata when making service-service requests

cprc & jsonclient: support request modifiers

---

lib/clog/clog.go

if your error gets wrapped you see:
`error = "my wrapper: my_cher_code"`
now you also see the underlying cher code:
`error_code = "my_cher_code"`
this helps to do analytics and log filtering on underlying errors.

clog: show underlying cher error_code

---

lib/clog/clog.go
lib/config/aws.go

this allows me to configure sidecars that are configured using env vars to easily re-use the clog and aws configuration libraries.

clog and aws add env config struct tags

---

lib/clog/clog.go
lib/config/aws.go

Change env names for logging to make them simpler. Previously I was adding a prefix in the application `LOG_`
But now I just keep them as fully qualified here.

Improve log env names

---

tools/cdep/app/add_config.go

this makes cdep also update image tags for sidecars that use the same source repository as the main container.
this means that the sidecars for consuming crpc-queues will track the same released build as the main container.
we may need to do something more complicated in future but this works for now.

cdep also update image tags in json

---

tools/cdep/app/dashboards.go
tools/cdep/app/update.go

Example 
```
INFO[0000] getting latest commit hash
INFO[0004] fetching config repo
INFO[0005] opening config repo
INFO[0005] pulling config repo from remote
INFO[0007] adding hash and branch to json files
INFO[0007] loading ALL environments
WARN[0012] Custom branch is going to be overriden, old: dlr-quote-enable-bgr, new: master, path: /Users/jules/code/config/nonprod/avocado/service/service-quote.yaml
Override branch? (y/n) n
Deployment Status
https://app.datadoghq.eu/logs?agg_m=count&agg_m_source=base&agg_q=%40_commit_hash%2Cstatus&agg_q_source=base%2Cbase&agg_t=count&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%2C%22value%22%5D&cols=service%2C%40level%2C%40rpc_method%2C%40message%2C%40error%2C%40http_duration&fromUser=true&from_ts=1739785059959&live=true&messageDispl …
```

cdep: provide datadog dashboard URLs

---

tools/cdep/app/add_config.go

if the json file doesn't contain any other fields, it needs to remove the extra comma it added.

cdep: don't break some json files with extra commas

---

lib/clog/clog.go
lib/clog/clog_test.go

This allows you to add the Cher meta and reasons to an error handle that logs and continues.
E.g.
```
clog.WithCherFields(clog.Get(ctx)).
WithField("segment_id", p.ID), err).
Error(fmt.Errorf("skipping policy: %w", err))
```

clog: add func WithCherFields

---

lib/crpc/HEADERS.md
lib/crpc/server.go
lib/crpc/server_test.go
lib/crpc/test/example_headers_test.go

This pull request introduces comprehensive support for HTTP header manipulation in the CRPC `Request` struct, enabling developers to read, set, add, and delete headers in a structured and case-insensitive manner. It also includes extensive documentation, tests, and examples to demonstrate the new functionality.
* **Header Support in `Request` Struct**:
- Added a `Header` field of type `http.Header` to the `Request` struct for storing HTTP headers.
- Updated the `ServeHTTP` method to populate the `Header` field from incoming HTTP requests.
* **New Header Manipulation Methods**:
- Introduced `GetHeader`, `SetHeader`, `AddHeader`, and `DelHeader` methods for accessing and modifying headers in a case-insensitive manner. These methods ensure nil safety and use Go's …

crpc: add availability to set/get headers
